serviceName: api_gateway_service
grpc:
  readerServicePort: :5004
http:
  port: :5001
  development: true
  basePath: /api/v1
  feedbacksPath: /api/v1/feedbacks
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "localhost:9092" ]
  groupID: api_gateway_consumer
  initTopics: true
kafkaTopics:
  feedbackRaw:
    topicName: feedback_raw
    partitions: 10
    replicationFactor: 1
  feedbackAnalyzed:
    topicName: feedback_analyzed
    partitions: 10
    replicationFactor: 1
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
jaeger:
  enable: true
  serviceName: api_gateway_service
  hostPort: "localhost:6831"
  logSpans: false