# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nlp_worker_reader/nlp_worker_reader.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/nlp_worker_reader/nlp_worker_reader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/proto/nlp_worker_reader/nlp_worker_reader.proto\x12\rreaderService\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n\x19\x43reateFeedbackAnalysisReq\x12\x13\n\x0b\x66\x65\x65\x64\x62\x61\x63k_id\x18\x01 \x01(\t\x12\x17\n\x0f\x66\x65\x65\x64\x62\x61\x63k_source\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xac\x01\n\x19\x43reateFeedbackAnalysisRes\x12\x13\n\x0b\x66\x65\x65\x64\x62\x61\x63k_id\x18\x01 \x01(\t\x12\x17\n\x0f\x66\x65\x65\x64\x62\x61\x63k_source\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08keywords\x18\x05 \x01(\t\x12\x11\n\tsentiment\x18\x06 \x01(\t2\x80\x01\n\x10NlpWorkerService\x12l\n\x16\x43reateFeedbackAnalysis\x12(.readerService.CreateFeedbackAnalysisReq\x1a(.readerService.CreateFeedbackAnalysisResB\x12Z\x10./;readerServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nlp_worker_reader.nlp_worker_reader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020./;readerService'
  _globals['_CREATEFEEDBACKANALYSISREQ']._serialized_start=100
  _globals['_CREATEFEEDBACKANALYSISREQ']._serialized_end=235
  _globals['_CREATEFEEDBACKANALYSISRES']._serialized_start=238
  _globals['_CREATEFEEDBACKANALYSISRES']._serialized_end=410
  _globals['_NLPWORKERSERVICE']._serialized_start=413
  _globals['_NLPWORKERSERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
