# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.nlp_worker_reader import nlp_worker_reader_pb2 as proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/nlp_worker_reader/nlp_worker_reader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NlpWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFeedbackAnalysis = channel.unary_unary(
                '/readerService.NlpWorkerService/CreateFeedbackAnalysis',
                request_serializer=proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2.CreateFeedbackAnalysisReq.SerializeToString,
                response_deserializer=proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2.CreateFeedbackAnalysisRes.FromString,
                _registered_method=True)


class NlpWorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFeedbackAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFeedbackAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFeedbackAnalysis,
                    request_deserializer=proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2.CreateFeedbackAnalysisReq.FromString,
                    response_serializer=proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2.CreateFeedbackAnalysisRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'readerService.NlpWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('readerService.NlpWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NlpWorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFeedbackAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/readerService.NlpWorkerService/CreateFeedbackAnalysis',
            proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2.CreateFeedbackAnalysisReq.SerializeToString,
            proto_dot_nlp__worker__reader_dot_nlp__worker__reader__pb2.CreateFeedbackAnalysisRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
