apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  ports:
  - port: 16686
    name: ui
    targetPort: 16686
  - port: 6831
    name: agent
    targetPort: 6831
    protocol: UDP
  - port: 14250
    name: collector
    targetPort: 14250
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 6831
          name: agent
          protocol: UDP
        - containerPort: 14250
          name: collector
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

