// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: feedback_reader.proto

package readerService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_feedback_reader_proto protoreflect.FileDescriptor

const file_feedback_reader_proto_rawDesc = "" +
	"\n" +
	"\x15feedback_reader.proto\x12\rreaderService\x1a\x1efeedback_reader_messages.proto2\xbb\x01\n" +
	"\x0eFeedbackReader\x12T\n" +
	"\x0eCreateFeedback\x12 .readerService.CreateFeedbackReq\x1a .readerService.CreateFeedbackRes\x12S\n" +
	"\vGetFeedback\x12!.readerService.GetFeedbackByIdReq\x1a!.readerService.GetFeedbackByIdResB\x12Z\x10./;readerServiceb\x06proto3"

var file_feedback_reader_proto_goTypes = []any{
	(*CreateFeedbackReq)(nil),  // 0: readerService.CreateFeedbackReq
	(*GetFeedbackByIdReq)(nil), // 1: readerService.GetFeedbackByIdReq
	(*CreateFeedbackRes)(nil),  // 2: readerService.CreateFeedbackRes
	(*GetFeedbackByIdRes)(nil), // 3: readerService.GetFeedbackByIdRes
}
var file_feedback_reader_proto_depIdxs = []int32{
	0, // 0: readerService.FeedbackReader.CreateFeedback:input_type -> readerService.CreateFeedbackReq
	1, // 1: readerService.FeedbackReader.GetFeedback:input_type -> readerService.GetFeedbackByIdReq
	2, // 2: readerService.FeedbackReader.CreateFeedback:output_type -> readerService.CreateFeedbackRes
	3, // 3: readerService.FeedbackReader.GetFeedback:output_type -> readerService.GetFeedbackByIdRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feedback_reader_proto_init() }
func file_feedback_reader_proto_init() {
	if File_feedback_reader_proto != nil {
		return
	}
	file_feedback_reader_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_reader_proto_rawDesc), len(file_feedback_reader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedback_reader_proto_goTypes,
		DependencyIndexes: file_feedback_reader_proto_depIdxs,
	}.Build()
	File_feedback_reader_proto = out.File
	file_feedback_reader_proto_goTypes = nil
	file_feedback_reader_proto_depIdxs = nil
}
