// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: feedback_reader_messages.proto

package readerService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feedback struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeedbackID        string                 `protobuf:"bytes,1,opt,name=FeedbackID,proto3" json:"FeedbackID,omitempty"`
	FeedbackSource    string                 `protobuf:"bytes,2,opt,name=FeedbackSource,proto3" json:"FeedbackSource,omitempty"`
	Text              string                 `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Keywords          []string               `protobuf:"bytes,4,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	Sentiment         string                 `protobuf:"bytes,5,opt,name=Sentiment,proto3" json:"Sentiment,omitempty"`
	FeedbackTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=FeedbackTimestamp,proto3" json:"FeedbackTimestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_feedback_reader_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_reader_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_feedback_reader_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetFeedbackID() string {
	if x != nil {
		return x.FeedbackID
	}
	return ""
}

func (x *Feedback) GetFeedbackSource() string {
	if x != nil {
		return x.FeedbackSource
	}
	return ""
}

func (x *Feedback) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Feedback) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Feedback) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *Feedback) GetFeedbackTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FeedbackTimestamp
	}
	return nil
}

type CreateFeedbackReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeedbackID        string                 `protobuf:"bytes,1,opt,name=FeedbackID,proto3" json:"FeedbackID,omitempty"`
	FeedbackSource    string                 `protobuf:"bytes,2,opt,name=FeedbackSource,proto3" json:"FeedbackSource,omitempty"`
	Text              string                 `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Keywords          []string               `protobuf:"bytes,4,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	Sentiment         string                 `protobuf:"bytes,5,opt,name=Sentiment,proto3" json:"Sentiment,omitempty"`
	FeedbackTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=FeedbackTimestamp,proto3" json:"FeedbackTimestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFeedbackReq) Reset() {
	*x = CreateFeedbackReq{}
	mi := &file_feedback_reader_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackReq) ProtoMessage() {}

func (x *CreateFeedbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_reader_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackReq.ProtoReflect.Descriptor instead.
func (*CreateFeedbackReq) Descriptor() ([]byte, []int) {
	return file_feedback_reader_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFeedbackReq) GetFeedbackID() string {
	if x != nil {
		return x.FeedbackID
	}
	return ""
}

func (x *CreateFeedbackReq) GetFeedbackSource() string {
	if x != nil {
		return x.FeedbackSource
	}
	return ""
}

func (x *CreateFeedbackReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateFeedbackReq) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *CreateFeedbackReq) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *CreateFeedbackReq) GetFeedbackTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FeedbackTimestamp
	}
	return nil
}

type CreateFeedbackRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackID    string                 `protobuf:"bytes,1,opt,name=FeedbackID,proto3" json:"FeedbackID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackRes) Reset() {
	*x = CreateFeedbackRes{}
	mi := &file_feedback_reader_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRes) ProtoMessage() {}

func (x *CreateFeedbackRes) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_reader_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRes.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRes) Descriptor() ([]byte, []int) {
	return file_feedback_reader_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFeedbackRes) GetFeedbackID() string {
	if x != nil {
		return x.FeedbackID
	}
	return ""
}

type GetFeedbackByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackID    string                 `protobuf:"bytes,1,opt,name=FeedbackID,proto3" json:"FeedbackID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByIdReq) Reset() {
	*x = GetFeedbackByIdReq{}
	mi := &file_feedback_reader_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByIdReq) ProtoMessage() {}

func (x *GetFeedbackByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_reader_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByIdReq.ProtoReflect.Descriptor instead.
func (*GetFeedbackByIdReq) Descriptor() ([]byte, []int) {
	return file_feedback_reader_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedbackByIdReq) GetFeedbackID() string {
	if x != nil {
		return x.FeedbackID
	}
	return ""
}

type GetFeedbackByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *Feedback              `protobuf:"bytes,1,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByIdRes) Reset() {
	*x = GetFeedbackByIdRes{}
	mi := &file_feedback_reader_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByIdRes) ProtoMessage() {}

func (x *GetFeedbackByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_reader_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByIdRes.ProtoReflect.Descriptor instead.
func (*GetFeedbackByIdRes) Descriptor() ([]byte, []int) {
	return file_feedback_reader_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedbackByIdRes) GetFeedback() *Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

var File_feedback_reader_messages_proto protoreflect.FileDescriptor

const file_feedback_reader_messages_proto_rawDesc = "" +
	"\n" +
	"\x1efeedback_reader_messages.proto\x12\rreaderService\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\bFeedback\x12\x1e\n" +
	"\n" +
	"FeedbackID\x18\x01 \x01(\tR\n" +
	"FeedbackID\x12&\n" +
	"\x0eFeedbackSource\x18\x02 \x01(\tR\x0eFeedbackSource\x12\x12\n" +
	"\x04Text\x18\x03 \x01(\tR\x04Text\x12\x1a\n" +
	"\bKeywords\x18\x04 \x03(\tR\bKeywords\x12\x1c\n" +
	"\tSentiment\x18\x05 \x01(\tR\tSentiment\x12H\n" +
	"\x11FeedbackTimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x11FeedbackTimestamp\"\xf3\x01\n" +
	"\x11CreateFeedbackReq\x12\x1e\n" +
	"\n" +
	"FeedbackID\x18\x01 \x01(\tR\n" +
	"FeedbackID\x12&\n" +
	"\x0eFeedbackSource\x18\x02 \x01(\tR\x0eFeedbackSource\x12\x12\n" +
	"\x04Text\x18\x03 \x01(\tR\x04Text\x12\x1a\n" +
	"\bKeywords\x18\x04 \x03(\tR\bKeywords\x12\x1c\n" +
	"\tSentiment\x18\x05 \x01(\tR\tSentiment\x12H\n" +
	"\x11FeedbackTimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x11FeedbackTimestamp\"3\n" +
	"\x11CreateFeedbackRes\x12\x1e\n" +
	"\n" +
	"FeedbackID\x18\x01 \x01(\tR\n" +
	"FeedbackID\"4\n" +
	"\x12GetFeedbackByIdReq\x12\x1e\n" +
	"\n" +
	"FeedbackID\x18\x01 \x01(\tR\n" +
	"FeedbackID\"I\n" +
	"\x12GetFeedbackByIdRes\x123\n" +
	"\bFeedback\x18\x01 \x01(\v2\x17.readerService.FeedbackR\bFeedbackB\x12Z\x10./;readerServiceb\x06proto3"

var (
	file_feedback_reader_messages_proto_rawDescOnce sync.Once
	file_feedback_reader_messages_proto_rawDescData []byte
)

func file_feedback_reader_messages_proto_rawDescGZIP() []byte {
	file_feedback_reader_messages_proto_rawDescOnce.Do(func() {
		file_feedback_reader_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_reader_messages_proto_rawDesc), len(file_feedback_reader_messages_proto_rawDesc)))
	})
	return file_feedback_reader_messages_proto_rawDescData
}

var file_feedback_reader_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_feedback_reader_messages_proto_goTypes = []any{
	(*Feedback)(nil),              // 0: readerService.Feedback
	(*CreateFeedbackReq)(nil),     // 1: readerService.CreateFeedbackReq
	(*CreateFeedbackRes)(nil),     // 2: readerService.CreateFeedbackRes
	(*GetFeedbackByIdReq)(nil),    // 3: readerService.GetFeedbackByIdReq
	(*GetFeedbackByIdRes)(nil),    // 4: readerService.GetFeedbackByIdRes
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_feedback_reader_messages_proto_depIdxs = []int32{
	5, // 0: readerService.Feedback.FeedbackTimestamp:type_name -> google.protobuf.Timestamp
	5, // 1: readerService.CreateFeedbackReq.FeedbackTimestamp:type_name -> google.protobuf.Timestamp
	0, // 2: readerService.GetFeedbackByIdRes.Feedback:type_name -> readerService.Feedback
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_feedback_reader_messages_proto_init() }
func file_feedback_reader_messages_proto_init() {
	if File_feedback_reader_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_reader_messages_proto_rawDesc), len(file_feedback_reader_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedback_reader_messages_proto_goTypes,
		DependencyIndexes: file_feedback_reader_messages_proto_depIdxs,
		MessageInfos:      file_feedback_reader_messages_proto_msgTypes,
	}.Build()
	File_feedback_reader_messages_proto = out.File
	file_feedback_reader_messages_proto_goTypes = nil
	file_feedback_reader_messages_proto_depIdxs = nil
}
