apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30501
    - port: 8001
      targetPort: 8001
      nodePort: 30801
